import { readLegacyNamespace } from '../leaf/read-legacy-namespace.js';
import '../leaf/firebase-config-internal.js';
import './firebase-auth-internal.js';
import './firebase-firestore-internal.js';
import './firebase-backup-merge-internal.js';
import './firebase-backup-internal.js';
import '../../firebase-storage.js';

const exportNames = [
  '_saveSession',
  'fbSignIn',
  'fbSignUp',
  'fbUpdateProfile',
  'fbSendVerificationEmail',
  'fbSendPasswordResetEmail',
  'fbCheckEmailVerified',
  'fbRefreshToken',
  'fbToken',
  'fbSignOut',
  'fbIsLoggedIn',
  'fbHeaders',
  'fbGet',
  'fbSet',
  'fbDel',
  'fbList',
  'fbGet3',
  'fbSet3',
  'fbDel3',
  'fbList3',
  'exportFullAccountBackup',
  'validateFullAccountBackup',
  'previewFullAccountBackupImport',
  'importFullAccountBackup',
  'debugNutritionStorage',
  'FB_PROJECT',
  'FB_KEY',
  'FB_BASE',
  'AUTH_BASE',
  'TOKEN_BASE',
  'REPORT_SERVER_URL',
  'REPORTS_ENABLED',
  'storage',
];

const FirebaseStorage = readLegacyNamespace(
  globalThis,
  'FirebaseStorage',
  exportNames,
);

Object.assign(globalThis, FirebaseStorage);

const {
  _saveSession,
  fbSignIn,
  fbSignUp,
  fbUpdateProfile,
  fbSendVerificationEmail,
  fbSendPasswordResetEmail,
  fbCheckEmailVerified,
  fbRefreshToken,
  fbToken,
  fbSignOut,
  fbIsLoggedIn,
  fbHeaders,
  fbGet,
  fbSet,
  fbDel,
  fbList,
  fbGet3,
  fbSet3,
  fbDel3,
  fbList3,
  exportFullAccountBackup,
  validateFullAccountBackup,
  previewFullAccountBackupImport,
  importFullAccountBackup,
  debugNutritionStorage,
  FB_PROJECT,
  FB_KEY,
  FB_BASE,
  AUTH_BASE,
  TOKEN_BASE,
  REPORT_SERVER_URL,
  REPORTS_ENABLED,
  storage,
} = FirebaseStorage;

export {
  AUTH_BASE,
  FB_BASE,
  FB_KEY,
  FB_PROJECT,
  REPORTS_ENABLED,
  REPORT_SERVER_URL,
  TOKEN_BASE,
  _saveSession,
  debugNutritionStorage,
  exportFullAccountBackup,
  fbCheckEmailVerified,
  fbDel,
  fbDel3,
  fbGet,
  fbGet3,
  fbHeaders,
  fbIsLoggedIn,
  fbList,
  fbList3,
  fbRefreshToken,
  fbSendPasswordResetEmail,
  fbSendVerificationEmail,
  fbSet,
  fbSet3,
  fbSignIn,
  fbSignOut,
  fbSignUp,
  fbToken,
  fbUpdateProfile,
  importFullAccountBackup,
  previewFullAccountBackupImport,
  storage,
  validateFullAccountBackup,
};
