import '../../meal-score.js';
import { readLegacyNamespace } from './read-legacy-namespace.js';

const {
  ALGORITHM_VERSION,
  HISTORICAL_ALGORITHM_VERSIONS,
  DEFAULT_WINDOW_HOURS,
  DEFAULT_CONFIG,
  hoursUntilLocalMidnight,
  hoursUntilCivilMidnight,
  timeShare,
  contextualTimeShare,
  maximizeScore,
  budgetScore,
  targetScore,
  limitScore,
  calculateMealScore,
  buildMealScoreSnapshot,
  inspectMealScoreSnapshot,
  areMealScoreSnapshotsComparable,
  collectValidMealEvaluationGroups,
  stripMealEvaluationMetadata,
  invalidateMealEvaluationForEntry,
} = readLegacyNamespace(globalThis, 'MealScore', [
  'ALGORITHM_VERSION',
  'HISTORICAL_ALGORITHM_VERSIONS',
  'DEFAULT_WINDOW_HOURS',
  'DEFAULT_CONFIG',
  'hoursUntilLocalMidnight',
  'hoursUntilCivilMidnight',
  'timeShare',
  'contextualTimeShare',
  'maximizeScore',
  'budgetScore',
  'targetScore',
  'limitScore',
  'calculateMealScore',
  'buildMealScoreSnapshot',
  'inspectMealScoreSnapshot',
  'areMealScoreSnapshotsComparable',
  'collectValidMealEvaluationGroups',
  'stripMealEvaluationMetadata',
  'invalidateMealEvaluationForEntry',
]);

export {
  ALGORITHM_VERSION,
  HISTORICAL_ALGORITHM_VERSIONS,
  DEFAULT_WINDOW_HOURS,
  DEFAULT_CONFIG,
  hoursUntilLocalMidnight,
  hoursUntilCivilMidnight,
  timeShare,
  contextualTimeShare,
  maximizeScore,
  budgetScore,
  targetScore,
  limitScore,
  calculateMealScore,
  buildMealScoreSnapshot,
  inspectMealScoreSnapshot,
  areMealScoreSnapshotsComparable,
  collectValidMealEvaluationGroups,
  stripMealEvaluationMetadata,
  invalidateMealEvaluationForEntry,
};
